name: python-workshop
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.10
  - jupyterlab=3.6.3
  - plotnine=0.10.1
  - pandas=1.4.0
  - numpy=1.24.2
  # The quatro package on conda-forge currently appears broken
  # Once this is fixed we should install quarto this way
  # - quarto